/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import social.Usuario;

/**
 *
 * @author aluno
 */
public class TelaFotos extends javax.swing.JPanel {

    /**
     * Creates new form TelaFotos
     */
    public TelaFotos(Usuario usuario) {
        initComponents();
        
        ArrayList<File> fotos = usuario.getFotos();
        //File foto = fotos.get(0);
        
        //Icon icon = new ImageIcon(foto.getPath());
        //lbnFoto.setIcon(icon);
        //lbnFoto.setText(TOOL_TIP_TEXT_KEY);
               
    }

    TelaFotos() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFotos = new javax.swing.JLabel();
        lblFoto1 = new javax.swing.JPanel();
        lbnFoto = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        lblFotos = new javax.swing.JLabel();

        btnFotos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnFotos.setText("FOTOS");

        javax.swing.GroupLayout lblFoto1Layout = new javax.swing.GroupLayout(lblFoto1);
        lblFoto1.setLayout(lblFoto1Layout);
        lblFoto1Layout.setHorizontalGroup(
            lblFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        lblFoto1Layout.setVerticalGroup(
            lblFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        lbnFoto.setText("FOTOS");

        setLayout(new java.awt.GridLayout(2, 2, 2, 2));

        lblFotos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFotos.setText("FOTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(lblFotos)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotos)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnFotos;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lblFoto1;
    private javax.swing.JLabel lblFotos;
    private javax.swing.JLabel lbnFoto;
    // End of variables declaration//GEN-END:variables
}
